"""membros: add observacao

Revision ID: 0ed8dcb3cc9b
Revises: 88a8b1ee3432
Create Date: 2025-08-24 18:28:24.265490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed8dcb3cc9b'
down_revision = '88a8b1ee3432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###
