"""membros: add foto_path

Revision ID: 570cadc5be07
Revises: 0ed8dcb3cc9b
Create Date: 2025-08-24 20:51:15.089021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570cadc5be07'
down_revision = '0ed8dcb3cc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.drop_column('foto_path')

    # ### end Alembic commands ###
