"""add membro_relacionamentos

Revision ID: 6439eeb666e4
Revises: deb5d07edae1
Create Date: 2025-08-24 06:54:05.068217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6439eeb666e4'
down_revision = 'deb5d07edae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membro_relacionamentos',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('source_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('target_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('degree', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['membros.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['membros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'degree', name='uq_rel_source_target_degree')
    )
    with op.batch_alter_table('membro_relacionamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membro_relacionamentos_degree'), ['degree'], unique=False)
        batch_op.create_index(batch_op.f('ix_membro_relacionamentos_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membro_relacionamentos_target_id'), ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro_relacionamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membro_relacionamentos_target_id'))
        batch_op.drop_index(batch_op.f('ix_membro_relacionamentos_source_id'))
        batch_op.drop_index(batch_op.f('ix_membro_relacionamentos_degree'))

    op.drop_table('membro_relacionamentos')
    # ### end Alembic commands ###
