"""add lookups table

Revision ID: 97d63d8180c7
Revises: 30f5ad6f47ee
Create Date: 2025-08-23 07:04:56.152145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97d63d8180c7'
down_revision = '30f5ad6f47ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookups',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value', name='uq_lookups_type_value')
    )
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookups_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookups_type'))

    op.drop_table('lookups')
    # ### end Alembic commands ###
