"""hist: membro_historico + data_inclusao

Revision ID: 9a132f54d093
Revises: 6439eeb666e4
Create Date: 2025-08-24 18:04:28.559933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a132f54d093'
down_revision = '6439eeb666e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inclusao', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.drop_column('data_inclusao')

    # ### end Alembic commands ###
