"""initial

Revision ID: b8a24a67ca8a
Revises: 
Create Date: 2025-08-22 06:09:24.890597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8a24a67ca8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('failed_jobs_uuid_unique'))

    op.drop_table('failed_jobs')
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('site_settings_key_unique'))

    op.drop_table('site_settings')
    op.drop_table('contacts')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('reports_row_hash_unique'))
        batch_op.drop_index(batch_op.f('reports_search_text_fulltext'), mysql_prefix='FULLTEXT')

    op.drop_table('reports')
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('lookups_type_name_unique'))

    op.drop_table('lookups')
    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('personal_access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('personal_access_tokens_token_unique'))
        batch_op.drop_index(batch_op.f('personal_access_tokens_tokenable_type_tokenable_id_index'))

    op.drop_table('personal_access_tokens')
    op.drop_table('migrations')
    op.drop_table('login_history')
    with op.batch_alter_table('membro_amigos', schema=None) as batch_op:
        batch_op.alter_column('membro_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('amigo_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('membro_amigos_amigo_id_foreign'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('membro_amigos_membro_id_foreign'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'membros', ['membro_id'], ['id'])
        batch_op.create_foreign_key(None, 'membros', ['amigo_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
        batch_op.alter_column('sexo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('concurso',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('telefone_unidade',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('telefone_celular',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('membros_cargo_efetivo_index'))
        batch_op.drop_index(batch_op.f('membros_comarca_lotacao_index'))
        batch_op.drop_index(batch_op.f('membros_nome_index'))
        batch_op.create_index(batch_op.f('ix_membros_nome'), ['nome'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=191), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=191),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=191),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'user', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('two_factor_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_index(batch_op.f('users_google_id_unique'))
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('phone')
        batch_op.drop_column('google_id')
        batch_op.drop_column('password')
        batch_op.drop_column('avatar')
        batch_op.drop_column('two_factor_expires_at')
        batch_op.drop_column('remember_token')
        batch_op.drop_column('two_factor_code')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True))
        batch_op.add_column(sa.Column('remember_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('two_factor_expires_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.add_column(sa.Column('google_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.create_index(batch_op.f('users_google_id_unique'), ['google_id'], unique=True)
        batch_op.alter_column('two_factor_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('role',
               existing_type=sa.String(length=32),
               type_=mysql.ENUM('admin', 'user', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('email',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('membros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_membros_nome'))
        batch_op.create_index(batch_op.f('membros_nome_index'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('membros_comarca_lotacao_index'), ['comarca_lotacao'], unique=False)
        batch_op.create_index(batch_op.f('membros_cargo_efetivo_index'), ['cargo_efetivo'], unique=False)
        batch_op.alter_column('telefone_celular',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('telefone_unidade',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('concurso',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('sexo',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('membro_amigos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('membro_amigos_membro_id_foreign'), 'membros', ['membro_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('membro_amigos_amigo_id_foreign'), 'membros', ['amigo_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('amigo_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('membro_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)

    op.create_table('login_history',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('first_login_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('last_login_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('login_history_user_id_foreign'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('migrations',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('migration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('batch', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('personal_access_tokens',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tokenable_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('tokenable_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('abilities', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('last_used_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('personal_access_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('personal_access_tokens_tokenable_type_tokenable_id_index'), ['tokenable_type', 'tokenable_id'], unique=False)
        batch_op.create_index(batch_op.f('personal_access_tokens_token_unique'), ['token'], unique=True)

    op.create_table('password_reset_tokens',
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('lookups',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('lookups_type_name_unique'), ['type', 'name'], unique=True)

    op.create_table('reports',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('data', mysql.JSON(), nullable=False),
    sa.Column('search_text', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('row_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('reports_search_text_fulltext'), ['search_text'], unique=False, mysql_prefix='FULLTEXT')
        batch_op.create_index(batch_op.f('reports_row_hash_unique'), ['row_hash'], unique=True)

    op.create_table('contacts',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('subject', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'answered', 'closed'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('admin_response', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('responded_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('site_settings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('value', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("'text'"), nullable=False),
    sa.Column('group', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("'general'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('site_settings_key_unique'), ['key'], unique=True)

    op.create_table('failed_jobs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('connection', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('queue', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('payload', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('exception', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('failed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('failed_jobs_uuid_unique'), ['uuid'], unique=True)

    # ### end Alembic commands ###
