"""users_py add phone active

Revision ID: d1bbcf4490dd
Revises: 97d63d8180c7
Create Date: 2025-08-23 09:37:34.398881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bbcf4490dd'
down_revision = '97d63d8180c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_py', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_py', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
