"""users_py add reset_code and reset_expires_at

Revision ID: deb5d07edae1
Revises: d1bbcf4490dd
Create Date: 2025-08-23 10:10:53.426873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb5d07edae1'
down_revision = 'd1bbcf4490dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_py', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reset_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_py', schema=None) as batch_op:
        batch_op.drop_column('reset_expires_at')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
